runtime: nodejs
env: flex

env_variables:
  DB_USER: root
  DB_PASS: fuckyoubaby
  DB_NAME: movies
  CLOUD_SQL_CONNECTION_NAME: monir-274101:us-central1:movies

beta_settings:
  cloud_sql_instances: monir-274101:us-central1:movies

